replace plugin.xml with plugin dot xml for JDK 11
without it for openjdk 11.0.1 2018-10-16

java.lang.ClassFormatError: Illegal method name "Test that a correct plugin.xml file is generated when the plugin.xml doesn't exist" in class org/grails/compiler/injection/GlobalGrailsClassInjectorTransformationSpec$1
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.grails.compiler.injection.GlobalGrailsClassInjectorTransformationSpec.Test that a correct plugin.xml file is generated when the plugin.xml doesn't exist(GlobalGrailsClassInjectorTransformationSpec.groovy:27)