Revamp branch `2.5.x` (#13285)
* Upgrade Gradle wrapper to version 3.5

* Remove legacy Gradle plugin "net.gvmtool.sdkvendor"

* Update artifact repositories

* Fix test artifact coordinates

* Fix Maven Central URL (HTTPS Required)

```
501 HTTPS Required.
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```

* Rename some problematic test methods

```
java.lang.ClassFormatError: Illegal method name "tag output must not be automatically encoded." in class org/codehaus/groovy/grails/web/codecs/CodecSpec
```

* Replace CI system (Travis => GitHub Actions)

* Add release workflows